---
  
- name: Get Rancher Install Status for first time setup check
  delegate_to: localhost
  uri:
    url: "https://{{ rancher_hostname }}/ping"
    validate_certs: no
    return_content: true
    status_code:
    - -1 # For cases where nginx ingress controller is not yet ready
    - 200 # Rancher should be installed
    - 404 # Rancher is not yet installed
  register: rancher_installed
  check_mode: no
  changed_when: false

- name: Set Rancher install status
  set_fact:
    rancher_installed: "{{ rancher_installed.content.find('pong') != -1 }}"

- name: Rancher initial setup (only on first time setup)
  delegate_to: localhost
  import_tasks: rancher-initial-setup.yml
  when:
    - not rancher_installed
